version : '3'

services:
  django:
    build:
      context: ./Backend
    env_file:
      - /Backend/.env
    ports:
      - "8000:8000"
    volumes:
      - ./Backend:/app
    depends_on:
      - db
    command: python manage.py runserver 0.0.0.0:8000

  db:
    image: postgres:14
    env_file:
      - /Backend/.env
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    env_file:
      - /Backend/.env
    environment:
      - PGADMIN_DEFAULT_EMAIL=${DB_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${DB_PASSWORD}
      - PGADMIN_LISTEN_ADDRESS=0.0.0.0
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  postgres_data: