# Generated by Django 5.0 on 2023-12-29 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='premium_expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
